# Default values for notification.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: agnops/notification
  pullPolicy: Always
  # Overrides the image tag whose default is the chart version.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

slack:
  enabled: false
  webhookUrl: "https://hooks.slack.com/services/bla/bla/bla"

# For gmail, you have to enable less secure app access: https://myaccount.google.com/lesssecureapps
smtpDetails:
  enabled: false
  host: "smtp.gmail.com"
  port: "587"
  username: ""
  password: ""

mailgun:
  enabled: false
  # https://app.mailgun.com/app/account/security/api_keys
  apiKey: ""
  # https://app.mailgun.com/app/sending/domains
  domain: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
