{{- $fullName := include "webhook-manager.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webhook-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.webhookSecret }}
    WEBHOOK_SECRET: {{ .Values.webhookSecret }}
  {{- else }}
    WEBHOOK_SECRET: ""
  {{- end }}