apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-generator.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]