{{- $fullName := include "job-generator.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "job-generator.labels" . | nindent 4 }}
type: Opaque
stringData:
    WEBHOOK_PAYLOAD_URL: http{{ if $.Values.global.ingress.tls }}s{{ end }}://{{ index .Values.global.ingress.hosts 0 }}/webhooks