apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{- if .Values.slack.enabled }}
    SLACK_ENABLED: "TRUE"
    SLACK_WEBHOOK_URL: {{ .Values.slack.webhookUrl }}
    {{- else }}
    SLACK_ENABLED: "FALSE"
    {{- end }}
    {{- if .Values.smtpDetails.enabled }}
    SMTP_ENABLED: "TRUE"
    SMTP_HOST: {{ .Values.smtpDetails.host }}
    SMTP_PORT: "{{ .Values.smtpDetails.port }}"
    SMTP_USERNAME: {{ .Values.smtpDetails.username }}
    SMTP_PASSWORD: {{ .Values.smtpDetails.password }}
    {{- else }}
    SMTP_ENABLED: "FALSE"
    {{- end }}
    {{- if .Values.mailgun.enabled }}
    MAILGUN_ENABLED: "TRUE"
    MAILGUN_APIKEY: {{ .Values.mailgun.apiKey }}
    MAILGUN_DOMAIN: {{ .Values.mailgun.domain }}
    {{- else }}
    MAILGUN_ENABLED: "FALSE"
    {{- end }}