apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "oauth2-proxy.serviceAccountName" . }}
  apiGroup: ""
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "oauth2-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io